# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

# ---- NEW STEP: install cosign ----
    - name: Install cosign
      run: |
        curl -sSLf https://raw.githubusercontent.com/sigstore/cosign/main/install.sh | sudo bash

# ---- NEW STEP: verify npm package signatures ----
    - name: Verify dependency signatures
      run: |
        # npm 9+ supports signature verification directly
        npm audit signatures
